In [59]:
import pandas as pd
from matplotlib import pyplot as plt

sample_data = pd.read_csv('history.csv')




sample_data



year  returns
0   2018    -4.38
1   2017    21.83
2   2016    11.96
3   2015     1.38
4   2014    13.69
5   2013    32.39
6   2012    16.00
7   2011     2.11
8   2010    15.06
9   2009    26.46
10  2008   -37.00
11  2007     5.49
12  2006    15.79
13  2005     4.91
14  2004    10.88
15  2003    28.68
16  2002   -22.10
17  2001   -11.89
18  2000    -9.10
19  1999    21.04
20  1998    28.58
21  1997    33.36
22  1996    22.96
23  1995    37.58
24  1994     1.32
25  1993    10.08
26  1992     7.62
27  1991    30.47
28  1990    -3.10
29  1989    31.69
..   ...      ...
63  1955    31.56
64  1954    52.62
65  1953    -0.99
66  1952    18.37
67  1951    24.02
68  1950    31.71
69  1949    18.79
70  1948     5.50
71  1947     5.71
72  1946    -8.07
73  1945    36.44
74  1944    19.75
75  1943    25.90
76  1942    20.34
77  1941   -11.59
78  1940    -9.78
79  1939    -0.41
80  1938    31.12
81  1937   -35.03
82  1936    33.92
83  1935    47.67
84  1934    -1.44
85  1933    53.99
86  1932    -8.19
87  1931   -43.34
88  1930   -24.90
89  1929    -8.42
90  1928    43.61
91  1927    37.49
92  1926    11.62

[93 rows x 2 columns]

In [56]:
sample_data.returns[0]

-4.38

In [4]:
#annual s&p transition matrix
import pandas as pd
from matplotlib import pyplot as plt

sample_data = pd.read_csv('history.csv')


slota=0
slotb=0
slotc=0
slotd=0
slote=0
slotf=0
slotg=0
sloth=0
sloti=0
slotj=0
slotk=0
slotl=0
slotm=0
slotn=0
sloto=0
slotp=0

totw=0
totx=0
toty=0
totz=0

for i in range(1,92):
    if sample_data.returns[92 - (i-1)] <= -8 and sample_data.returns[(92 - i)] <= -8:
        totw = totw + 1
        slota =  slota + 1
    if sample_data.returns[92 - (i-1)] <= -8 and sample_data.returns[(92 - i)] > -8 and sample_data.returns[(92 - i)] <= 0:
        totw = totw + 1
        slotb =  slotb + 1
    if sample_data.returns[92 - (i-1)] <= -8 and sample_data.returns[(92 - i)] > 0 and sample_data.returns[(92 - i)] <= 8:
        totw = totw + 1
        slotc = slotc + 1
    if sample_data.returns[92 - (i-1)] <= -8 and sample_data.returns[(92 - i)] > 8:
        totw = totw + 1
        slotd =  slotd + 1
    if sample_data.returns[92 - (i-1)] > -8 and sample_data.returns[92 - (i-1)] <= 0 and sample_data.returns[(92 - i)] <= -8:
        totx = totx + 1
        slote =  slote + 1
    if sample_data.returns[92 - (i-1)] > -8 and sample_data.returns[92 - (i-1)] <= 0 and sample_data.returns[(92 - i)] > -8 and sample_data.returns[(92 - i)] <= 0:
        totx = totx + 1
        slotf =  slotf + 1
    if sample_data.returns[92 - (i-1)] > -8 and sample_data.returns[92 - (i-1)] <= 0 and sample_data.returns[(92 - i)] > 0 and sample_data.returns[(92 - i)] <= 8:
        totx = totx + 1
        slotg =  slotg + 1
    if sample_data.returns[92 - (i-1)] > -8 and sample_data.returns[92 - (i-1)] <= 0 and sample_data.returns[(92 - i)] > 8:
        totx = totx + 1
        sloth =  sloth + 1
    if sample_data.returns[92 - (i-1)] > 0 and sample_data.returns[92 - (i-1)] <= 8 and sample_data.returns[(92 - i)] <= -8:
        toty = toty + 1
        sloti =  sloti + 1
    if sample_data.returns[92 - (i-1)] > 0 and sample_data.returns[92 - (i-1)] <= 8 and sample_data.returns[(92 - i)] > -8 and sample_data.returns[(92 - i)] <= 0:
        toty = toty + 1
        slotj =  slotj + 1
    if sample_data.returns[92 - (i-1)] > 0 and sample_data.returns[92 - (i-1)] <= 8 and sample_data.returns[(92 - i)] > 0 and sample_data.returns[(92 - i)] <= 8:
        toty = toty + 1
        slotk =  slotk + 1
    if sample_data.returns[92 - (i-1)] > 0 and sample_data.returns[92 - (i-1)] <= 8 and sample_data.returns[(92 - i)] > -8:
        toty = toty + 1
        slotl =  slotl + 1
    if sample_data.returns[92 - (i-1)] > 8 and sample_data.returns[(92 - i)] <= -8:
        totz = totz + 1
        slotm =  slotm + 1
    if sample_data.returns[92 - (i-1)] > 8 and sample_data.returns[(92 - i)] > -8 and sample_data.returns[(92 - i)] <= 0:
        totz = totz + 1
        slotn =  slotn + 1
    if sample_data.returns[92 - (i-1)] > 8 and sample_data.returns[(92 - i)] > 0 and sample_data.returns[(92 - i)] <= 8:
        totz = totz + 1
        sloto =  sloto + 1
    if sample_data.returns[92 - (i-1)] > 8 and sample_data.returns[(92 - i)] > 8:
        totz = totz + 1
        slotp =  slotp + 1
        
        

import numpy as np

A = np.array([[slota/totw, slotb/totw, slotc/totw, slotd/totw], [slote/totx, slotf/totx, slotg/totx, sloth/totx],
             [sloti/toty, slotj/toty, slotk/toty, slotl/toty], [slotm/totz, slotn/totz, sloto/totz, slotp/totz]])
A
        
        
        
        

array([[0.38888889, 0.        , 0.11111111, 0.5       ],
       [0.16666667, 0.        , 0.16666667, 0.66666667],
       [0.13333333, 0.        , 0.06666667, 0.8       ],
       [0.1509434 , 0.11320755, 0.18867925, 0.54716981]])

In [8]:
#daily s&p transition matrix, past 10 yrs
import pandas as pd
from matplotlib import pyplot as plt

sample_data = pd.read_csv('S&P 500 Historical Data Daily 10yr.csv')

for i in range(0, len(sample_data.change)):
    sample_data.change[i] = sample_data.change[i][:-1]

slota=0
slotb=0
slotc=0
slotd=0
slote=0
slotf=0
slotg=0
sloth=0
sloti=0
slotj=0
slotk=0
slotl=0
slotm=0
slotn=0
sloto=0
slotp=0

totw=0
totx=0
toty=0
totz=0

for i in range(1,len(sample_data.change)):
    if float(sample_data.change[len(sample_data.change) - i]) <= -1.5 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= -1.5:
        totw = totw + 1
        slota =  slota + 1
    if float(sample_data.change[len(sample_data.change) - i]) <= -1.5 and float(sample_data.change[len(sample_data.change) - (i+1)]) > -1.5 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 0:
        totw = totw + 1
        slotb =  slotb + 1
    if float(sample_data.change[len(sample_data.change) - i]) <= -1.5 and float(sample_data.change[len(sample_data.change) - (i+1)]) > 0 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 1:
        totw = totw + 1
        slotc = slotc + 1
    if float(sample_data.change[len(sample_data.change) - i]) <= -1.5 and float(sample_data.change[len(sample_data.change) - (i+1)]) > 1:
        totw = totw + 1
        slotd =  slotd + 1
    if float(sample_data.change[len(sample_data.change) - i]) > -1.5 and float(sample_data.change[len(sample_data.change) - i]) <= 0 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= -1.5:
        totx = totx + 1
        slote =  slote + 1
    if float(sample_data.change[len(sample_data.change) - i]) > -1.5 and float(sample_data.change[len(sample_data.change) - i]) <= 0 and float(sample_data.change[len(sample_data.change) - (i+1)]) > -1.5 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 0:
        totx = totx + 1
        slotf =  slotf + 1
    if float(sample_data.change[len(sample_data.change) - i]) > -1.5 and float(sample_data.change[len(sample_data.change) - i]) <= 0 and float(sample_data.change[len(sample_data.change) - (i+1)]) > 0 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 1:
        totx = totx + 1
        slotg =  slotg + 1
    if float(sample_data.change[len(sample_data.change) - i]) > -1.5 and float(sample_data.change[len(sample_data.change) - i]) <= 0 and float(sample_data.change[len(sample_data.change) - (i+1)]) > 1:
        totx = totx + 1
        sloth =  sloth + 1
    if float(sample_data.change[len(sample_data.change) - i]) > 0 and float(sample_data.change[len(sample_data.change) - i]) <= 1 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= -1.5:
        toty = toty + 1
        sloti =  sloti + 1
    if float(sample_data.change[len(sample_data.change) - i]) > 0 and float(sample_data.change[len(sample_data.change) - i]) <= 1 and float(sample_data.change[len(sample_data.change) - (i+1)]) > -1.5 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 0:
        toty = toty + 1
        slotj =  slotj + 1
    if float(sample_data.change[len(sample_data.change) - i]) > 0 and float(sample_data.change[len(sample_data.change) - i]) <= 1 and float(sample_data.change[len(sample_data.change) - (i+1)]) > 0 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 1:
        toty = toty + 1
        slotk =  slotk + 1
    if float(sample_data.change[len(sample_data.change) - i]) > 0 and float(sample_data.change[len(sample_data.change) - i]) <= 1 and float(sample_data.change[len(sample_data.change) - (i+1)]) > 1:
        toty = toty + 1
        slotl =  slotl + 1
    if float(sample_data.change[len(sample_data.change) - i]) > 1 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= -1.5:
        totz = totz + 1
        slotm =  slotm + 1
    if float(sample_data.change[len(sample_data.change) - i]) > 1 and float(sample_data.change[len(sample_data.change) - (i+1)]) > -1.5 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 0:
        totz = totz + 1
        slotn =  slotn + 1
    if float(sample_data.change[len(sample_data.change) - i]) > 1 and float(sample_data.change[len(sample_data.change) - (i+1)]) > 0 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 1:
        totz = totz + 1
        sloto =  sloto + 1
    if float(sample_data.change[len(sample_data.change) - i]) > 1 and float(sample_data.change[len(sample_data.change) - (i+1)]) > 1:
        totz = totz + 1
        slotp =  slotp + 1
        
        




import numpy as np

A = np.array([[slota/totw, slotb/totw, slotc/totw, slotd/totw], [slote/totx, slotf/totx, slotg/totx, sloth/totx],
             [sloti/toty, slotj/toty, slotk/toty, slotl/toty], [slotm/totz, slotn/totz, sloto/totz, slotp/totz]])
A 



array([[0.14649682, 0.2611465 , 0.33757962, 0.25477707],
       [0.06766169, 0.37412935, 0.42985075, 0.12835821],
       [0.03714286, 0.43333333, 0.42666667, 0.10285714],
       [0.08359133, 0.41176471, 0.3622291 , 0.14241486]])

In [146]:
import pandas as pd
from matplotlib import pyplot as plt

(slotm + slotn + sloto + slotp)/totz


1.0

1


In [153]:
#slightly more efficient daily s&p transition matrix, 10yr daily
import pandas as pd
from matplotlib import pyplot as plt

sample_data = pd.read_csv('S&P 500 Historical Data Daily 10yr.csv')

for i in range(0, len(sample_data.change)):
    sample_data.change[i] = sample_data.change[i][:-1]

slota=0
slotb=0
slotc=0
slotd=0
slote=0
slotf=0
slotg=0
sloth=0
sloti=0
slotj=0
slotk=0
slotl=0
slotm=0
slotn=0
sloto=0
slotp=0

totw=0
totx=0
toty=0
totz=0

for i in range(1,len(sample_data.change)):
    
    if float(sample_data.change[len(sample_data.change) - i]) <= -1.5:
        totw = totw + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) <= -1.5:           
            slota =  slota + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > -1.5 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 0:
            slotb =  slotb + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 0 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 1:
            slotc = slotc + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 1:
            slotd =  slotd + 1
        
        
    if float(sample_data.change[len(sample_data.change) - i]) > -1.5 and float(sample_data.change[len(sample_data.change) - i]) <= 0:
        totx = totx + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) <= -1.5:
            slote =  slote + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > -1.5 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 0:
            slotf =  slotf + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 0 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 1:
            slotg =  slotg + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 1:
            sloth =  sloth + 1
        
        
    if float(sample_data.change[len(sample_data.change) - i]) > 0 and float(sample_data.change[len(sample_data.change) - i]) <= 1:
        toty = toty + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) <= -1.5:
            sloti =  sloti + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > -1.5 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 0:
            slotj =  slotj + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 0 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 1:
            slotk =  slotk + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 1:
            slotl =  slotl + 1
        
        
    if float(sample_data.change[len(sample_data.change) - i]) > 1:
        totz = totz + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) <= -1.5:
            slotm =  slotm + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > -1.5 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 0:
            slotn =  slotn + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 0 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 1:
            sloto =  sloto + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 1:
            slotp =  slotp + 1
        
        




import numpy as np

A = np.array([[slota/totw, slotb/totw, slotc/totw, slotd/totw], [slote/totx, slotf/totx, slotg/totx, sloth/totx],
             [sloti/toty, slotj/toty, slotk/toty, slotl/toty], [slotm/totz, slotn/totz, sloto/totz, slotp/totz]])
print(A) 

print(totw, totx, toty, totz)

[[0.14649682 0.2611465  0.33757962 0.25477707]
 [0.06766169 0.37412935 0.42985075 0.12835821]
 [0.03714286 0.43333333 0.42666667 0.10285714]
 [0.08359133 0.41176471 0.3622291  0.14241486]]
157 1005 1050 323


In [7]:
#slightly more efficient daily s&p transition matrix, 50yr monthly
import pandas as pd
from matplotlib import pyplot as plt

sample_data = pd.read_csv('S&P 500 Historical Data Monthly 50yr.csv')

for i in range(0, len(sample_data.change)):
    sample_data.change[i] = sample_data.change[i][:-1]

slota=0
slotb=0
slotc=0
slotd=0
slote=0
slotf=0
slotg=0
sloth=0
sloti=0
slotj=0
slotk=0
slotl=0
slotm=0
slotn=0
sloto=0
slotp=0

totw=0
totx=0
toty=0
totz=0

for i in range(1,len(sample_data.change)):
    
    if float(sample_data.change[len(sample_data.change) - i]) <= -5:
        totw = totw + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) <= -5:           
            slota =  slota + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > -5 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 0:
            slotb =  slotb + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 0 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 4:
            slotc = slotc + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 4:
            slotd =  slotd + 1
        
        
    if float(sample_data.change[len(sample_data.change) - i]) > -5 and float(sample_data.change[len(sample_data.change) - i]) <= 0:
        totx = totx + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) <= -5:
            slote =  slote + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > -5 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 0:
            slotf =  slotf + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 0 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 4:
            slotg =  slotg + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 4:
            sloth =  sloth + 1
        
        
    if float(sample_data.change[len(sample_data.change) - i]) > 0 and float(sample_data.change[len(sample_data.change) - i]) <= 4:
        toty = toty + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) <= -5:
            sloti =  sloti + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > -5 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 0:
            slotj =  slotj + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 0 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 4:
            slotk =  slotk + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 4:
            slotl =  slotl + 1
        
        
    if float(sample_data.change[len(sample_data.change) - i]) > 4:
        totz = totz + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) <= -5:
            slotm =  slotm + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > -5 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 0:
            slotn =  slotn + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 0 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 4:
            sloto =  sloto + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 4:
            slotp =  slotp + 1
        
        




import numpy as np

A = np.array([[slota/totw, slotb/totw, slotc/totw, slotd/totw], [slote/totx, slotf/totx, slotg/totx, sloth/totx],
             [sloti/toty, slotj/toty, slotk/toty, slotl/toty], [slotm/totz, slotn/totz, sloto/totz, slotp/totz]])
print(A) 

for i in range(1,2):
    A = A.dot(A)

print(totw, totx, toty, totz)
print((slota+slotb+slotc+slotd)/totw, (slote+slotf+slotg+sloth)/totx,
      (sloti+slotj+slotk+slotl)/toty, (slotm+slotn+sloto+slotp)/totz)

print(A)


[[0.27272727 0.25454545 0.18181818 0.29090909]
 [0.09392265 0.31491713 0.36464088 0.22651934]
 [0.06329114 0.35443038 0.4556962  0.12658228]
 [0.06956522 0.22608696 0.46956522 0.23478261]]
55 181 237 115
1.0 1.0 1.0 1.0
[[0.13003238 0.27979485 0.3618591  0.22831367]
 [0.09402952 0.30353326 0.40443957 0.19799765]
 [0.08819752 0.31785785 0.40784495 0.18609968]
 [0.08625904 0.30841563 0.4193136  0.18601173]]
