In [4]:
#returns daily S&P500 4x4 transition matrix based on past 10 yrs of daily S&P500 returns
#respective states from leftmost to rightmost column: 
#  change <= -1.5% 
#  -1.5% < change <= 0%
#  0% < change <= 1%
#  1% < change

import pandas as pd
from matplotlib import pyplot as plt

sample_data = pd.read_csv('S&P 500 Historical Data Daily 10yr.csv')

#eliminate '%' from the strings
for i in range(0, len(sample_data.change)):
    sample_data.change[i] = sample_data.change[i][:-1]

slota=0
slotb=0
slotc=0
slotd=0
slote=0
slotf=0
slotg=0
sloth=0
sloti=0
slotj=0
slotk=0
slotl=0
slotm=0
slotn=0
sloto=0
slotp=0

totw=0
totx=0
toty=0
totz=0

for i in range(1,len(sample_data.change)):
    
    if float(sample_data.change[len(sample_data.change) - i]) <= -1.5:
        totw = totw + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) <= -1.5:           
            slota =  slota + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > -1.5 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 0:
            slotb =  slotb + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 0 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 1:
            slotc = slotc + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 1:
            slotd =  slotd + 1
        
        
    if float(sample_data.change[len(sample_data.change) - i]) > -1.5 and float(sample_data.change[len(sample_data.change) - i]) <= 0:
        totx = totx + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) <= -1.5:
            slote =  slote + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > -1.5 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 0:
            slotf =  slotf + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 0 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 1:
            slotg =  slotg + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 1:
            sloth =  sloth + 1
        
        
    if float(sample_data.change[len(sample_data.change) - i]) > 0 and float(sample_data.change[len(sample_data.change) - i]) <= 1:
        toty = toty + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) <= -1.5:
            sloti =  sloti + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > -1.5 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 0:
            slotj =  slotj + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 0 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 1:
            slotk =  slotk + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 1:
            slotl =  slotl + 1
        
        
    if float(sample_data.change[len(sample_data.change) - i]) > 1:
        totz = totz + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) <= -1.5:
            slotm =  slotm + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > -1.5 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 0:
            slotn =  slotn + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 0 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 1:
            sloto =  sloto + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 1:
            slotp =  slotp + 1
        
        




import numpy as np

A = np.array([[slota/totw, slotb/totw, slotc/totw, slotd/totw], [slote/totx, slotf/totx, slotg/totx, sloth/totx],
             [sloti/toty, slotj/toty, slotk/toty, slotl/toty], [slotm/totz, slotn/totz, sloto/totz, slotp/totz]])
print(A) 



[[0.14649682 0.2611465  0.33757962 0.25477707]
 [0.06766169 0.37412935 0.42985075 0.12835821]
 [0.03714286 0.43333333 0.42666667 0.10285714]
 [0.08359133 0.41176471 0.3622291  0.14241486]]


In [2]:
#returns monthly S&P500 4x4 transition matrix based on past 50 yrs of monthly S&P500 returns
#respective states from leftmost to rightmost column: 
#  change <= -5% 
#  -5% < change <= 0%
#  0% < change <= 4%
#  4% < change

import pandas as pd
from matplotlib import pyplot as plt

sample_data = pd.read_csv('S&P 500 Historical Data Monthly 50yr.csv')

#eliminate '%' from the strings
for i in range(0, len(sample_data.change)):
    sample_data.change[i] = sample_data.change[i][:-1]

slota=0
slotb=0
slotc=0
slotd=0
slote=0
slotf=0
slotg=0
sloth=0
sloti=0
slotj=0
slotk=0
slotl=0
slotm=0
slotn=0
sloto=0
slotp=0

totw=0
totx=0
toty=0
totz=0

for i in range(1,len(sample_data.change)):
    
    if float(sample_data.change[len(sample_data.change) - i]) <= -5:
        totw = totw + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) <= -5:           
            slota =  slota + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > -5 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 0:
            slotb =  slotb + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 0 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 4:
            slotc = slotc + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 4:
            slotd =  slotd + 1
        
        
    if float(sample_data.change[len(sample_data.change) - i]) > -5 and float(sample_data.change[len(sample_data.change) - i]) <= 0:
        totx = totx + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) <= -5:
            slote =  slote + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > -5 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 0:
            slotf =  slotf + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 0 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 4:
            slotg =  slotg + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 4:
            sloth =  sloth + 1
        
        
    if float(sample_data.change[len(sample_data.change) - i]) > 0 and float(sample_data.change[len(sample_data.change) - i]) <= 4:
        toty = toty + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) <= -5:
            sloti =  sloti + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > -5 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 0:
            slotj =  slotj + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 0 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 4:
            slotk =  slotk + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 4:
            slotl =  slotl + 1
        
        
    if float(sample_data.change[len(sample_data.change) - i]) > 4:
        totz = totz + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) <= -5:
            slotm =  slotm + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > -5 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 0:
            slotn =  slotn + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 0 and float(sample_data.change[len(sample_data.change) - (i+1)]) <= 4:
            sloto =  sloto + 1
        if float(sample_data.change[len(sample_data.change) - (i+1)]) > 4:
            slotp =  slotp + 1
        
        


import numpy as np

A = np.array([[slota/totw, slotb/totw, slotc/totw, slotd/totw], [slote/totx, slotf/totx, slotg/totx, sloth/totx],
             [sloti/toty, slotj/toty, slotk/toty, slotl/toty], [slotm/totz, slotn/totz, sloto/totz, slotp/totz]])
print(A) 

[[0.27272727 0.25454545 0.18181818 0.29090909]
 [0.09392265 0.31491713 0.36464088 0.22651934]
 [0.06329114 0.35443038 0.4556962  0.12658228]
 [0.06956522 0.22608696 0.46956522 0.23478261]]


In [3]:
#returns annual S&P500 4x4 transition matrix based on past 92 yrs of yearly S&P500 returns
#respective states from leftmost to rightmost column: 
#  change <= -8% 
#  -8% < change <= 0%
#  0% < change <= 8%
#  8% < change
import pandas as pd
from matplotlib import pyplot as plt

sample_data = pd.read_csv('S&P 500 Historical Data Annual 92yr.csv')


slota=0
slotb=0
slotc=0
slotd=0
slote=0
slotf=0
slotg=0
sloth=0
sloti=0
slotj=0
slotk=0
slotl=0
slotm=0
slotn=0
sloto=0
slotp=0

totw=0
totx=0
toty=0
totz=0

for i in range(1,92):
    if sample_data.returns[92 - (i-1)] <= -8 and sample_data.returns[(92 - i)] <= -8:
        totw = totw + 1
        slota =  slota + 1
    if sample_data.returns[92 - (i-1)] <= -8 and sample_data.returns[(92 - i)] > -8 and sample_data.returns[(92 - i)] <= 0:
        totw = totw + 1
        slotb =  slotb + 1
    if sample_data.returns[92 - (i-1)] <= -8 and sample_data.returns[(92 - i)] > 0 and sample_data.returns[(92 - i)] <= 8:
        totw = totw + 1
        slotc = slotc + 1
    if sample_data.returns[92 - (i-1)] <= -8 and sample_data.returns[(92 - i)] > 8:
        totw = totw + 1
        slotd =  slotd + 1
    if sample_data.returns[92 - (i-1)] > -8 and sample_data.returns[92 - (i-1)] <= 0 and sample_data.returns[(92 - i)] <= -8:
        totx = totx + 1
        slote =  slote + 1
    if sample_data.returns[92 - (i-1)] > -8 and sample_data.returns[92 - (i-1)] <= 0 and sample_data.returns[(92 - i)] > -8 and sample_data.returns[(92 - i)] <= 0:
        totx = totx + 1
        slotf =  slotf + 1
    if sample_data.returns[92 - (i-1)] > -8 and sample_data.returns[92 - (i-1)] <= 0 and sample_data.returns[(92 - i)] > 0 and sample_data.returns[(92 - i)] <= 8:
        totx = totx + 1
        slotg =  slotg + 1
    if sample_data.returns[92 - (i-1)] > -8 and sample_data.returns[92 - (i-1)] <= 0 and sample_data.returns[(92 - i)] > 8:
        totx = totx + 1
        sloth =  sloth + 1
    if sample_data.returns[92 - (i-1)] > 0 and sample_data.returns[92 - (i-1)] <= 8 and sample_data.returns[(92 - i)] <= -8:
        toty = toty + 1
        sloti =  sloti + 1
    if sample_data.returns[92 - (i-1)] > 0 and sample_data.returns[92 - (i-1)] <= 8 and sample_data.returns[(92 - i)] > -8 and sample_data.returns[(92 - i)] <= 0:
        toty = toty + 1
        slotj =  slotj + 1
    if sample_data.returns[92 - (i-1)] > 0 and sample_data.returns[92 - (i-1)] <= 8 and sample_data.returns[(92 - i)] > 0 and sample_data.returns[(92 - i)] <= 8:
        toty = toty + 1
        slotk =  slotk + 1
    if sample_data.returns[92 - (i-1)] > 0 and sample_data.returns[92 - (i-1)] <= 8 and sample_data.returns[(92 - i)] > -8:
        toty = toty + 1
        slotl =  slotl + 1
    if sample_data.returns[92 - (i-1)] > 8 and sample_data.returns[(92 - i)] <= -8:
        totz = totz + 1
        slotm =  slotm + 1
    if sample_data.returns[92 - (i-1)] > 8 and sample_data.returns[(92 - i)] > -8 and sample_data.returns[(92 - i)] <= 0:
        totz = totz + 1
        slotn =  slotn + 1
    if sample_data.returns[92 - (i-1)] > 8 and sample_data.returns[(92 - i)] > 0 and sample_data.returns[(92 - i)] <= 8:
        totz = totz + 1
        sloto =  sloto + 1
    if sample_data.returns[92 - (i-1)] > 8 and sample_data.returns[(92 - i)] > 8:
        totz = totz + 1
        slotp =  slotp + 1
        
        

import numpy as np

A = np.array([[slota/totw, slotb/totw, slotc/totw, slotd/totw], [slote/totx, slotf/totx, slotg/totx, sloth/totx],
             [sloti/toty, slotj/toty, slotk/toty, slotl/toty], [slotm/totz, slotn/totz, sloto/totz, slotp/totz]])
A
     

array([[0.38888889, 0.        , 0.11111111, 0.5       ],
       [0.16666667, 0.        , 0.16666667, 0.66666667],
       [0.13333333, 0.        , 0.06666667, 0.8       ],
       [0.1509434 , 0.11320755, 0.18867925, 0.54716981]])